include: /build/gitlab-ci.yml

variables:
  PROJECT_PATH: "sosy-lab/software/java-smt"
  GH_REF: "github.com/sosy-lab/java-smt"
  # Version of https://gitlab.com/sosy-lab/software/refaster/ to use
  REFASTER_REPO_REVISION: 0c4e9686d53f4c681a74d06e73d180837af38d33
  # Needs to be synchronized with Error Prone version in lib/ivy.xml
  REFASTER_VERSION: 2.3.4

build:jdk-13:
  variables:
    # https://github.com/google/error-prone/issues/1106
    ANT_PROPS_BUILD: "-Divy.disable=true -Derrorprone.disable=true"
