# This file is part of JavaSMT,
# an API wrapper for a collection of SMT solvers:
# https://github.com/sosy-lab/java-smt
#
# SPDX-FileCopyrightText: 2020 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

include: /build/gitlab-ci.yml

variables:
  PROJECT_PATH: "sosy-lab/software/java-smt"
  GH_REF: "github.com/sosy-lab/java-smt"
  # Version of https://gitlab.com/sosy-lab/software/refaster/ to use
  REFASTER_REPO_REVISION: 1c7b66df1ee6460c3a7b04bc4495f440a093ece7
  # Needs to be synchronized with Error Prone version in lib/ivy.xml
  REFASTER_VERSION: 2.4.0

build:jdk-14:
  variables:
    # https://github.com/google/error-prone/issues/1106
    ANT_PROPS_BUILD: "-Divy.disable=true -Derrorprone.disable=true"
